// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://zaitvvwoqwdgtliocvtf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaXR2dndvcXdkZ3RsaW9jdnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMTEwNzAsImV4cCI6MjA4NTc4NzA3MH0.jQwaWsV_kcrrvbrYwSoy7yAkEZR6dTw4Ve3iMg5VCbU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});